/* global CASE_BANK — โหลดก่อนสคริปต์หลักใน index.html */
var CASE_BANK = [
  {
    id: 'fast',
    title: 'เคส 1 — Fast Track (มีผู้เห็น onset)',
    shortTitle: 'Fast Track',
    caseHtml: '<span class="case-tag">พระภิกษุ ~68 ปี</span><span class="case-tag">HT+DM+AF</span><span class="case-tag">Warfarin</span><br>ขณะนั่งฟังเทศในศาลา พระรูปที่อยู่ด้วยกันเห็นท่าน<strong>พูดไม่ชัด ปากเบี้ยว แขนซ้ายอ่อนแรงทันที เวลา 13:00 น.</strong><br>นำส่ง ER <strong>14:30 น.</strong> · <strong>BP 195/105</strong> · O₂Sat 96% RA · CT: No hemorrhage',
    questions: [
      { g: 'กลุ่มที่ 1 — Timeline & Onset', t: 'พระรูปที่อยู่ด้วยกันเห็นพระภิกษุท่านนี้มีอาการทันทีเวลา 13:00 น. Last Seen Normal (LSN) และ Stroke Onset คือเวลาใด?', h: 'Witnessed onset = เห็นเหตุการณ์เอง → LSN = Onset = เวลาที่เห็นอาการทันที', o: ['LSN=13:00, Onset=14:30 (เวลาถึง ER)', 'LSN=Onset=13:00 น. (พระรูปที่อยู่ด้วยกันเห็นทันที)', 'LSN=เช้าวันนี้, Onset=ไม่ทราบ', 'ต้องถามผู้เห็นเหตุการณ์เพิ่ม ยังสรุปไม่ได้'], a: 1, e: 'Witnessed onset = มีพระรูปที่อยู่ด้วยกันเห็นทันที → LSN = Onset = 13:00 น. ต่างจาก Wake-up stroke ที่ไม่รู้เวลา กรณีนี้ชัดเจนมากค่ะ' },
      { g: 'กลุ่มที่ 1 — Timeline & Onset', t: 'Stroke onset 13:00 น. ถึง ER 14:30 น. พระภิกษุรูปนี้อยู่ใน window การรักษาใด?', h: 'rt-PA ให้ได้ภายใน 4.5 ชม. จาก onset / Thrombectomy ให้ได้ภายใน 24 ชม.', o: ['เกิน window ทุกอย่างแล้ว — conservative เท่านั้น', 'อยู่ใน rt-PA window (onset 1.5 ชม.) และ Thrombectomy window', 'อยู่ใน Thrombectomy window เท่านั้น (4.5–24 ชม.)', 'ยังบอกไม่ได้ รอ CT ก่อน'], a: 1, e: 'Onset ถึง ER = 1.5 ชม. → อยู่ใน rt-PA window (≤4.5 ชม.) และ Thrombectomy window ด้วย แต่ยังต้องคัดกรองข้อห้ามด้วย Lab ตาม protocol (ไม่ได้แปลว่าต้องหยุดรอผลครบทุกรายการในทุกสถานการณ์)' },
      { g: 'กลุ่มที่ 2 — NIHSS & อาการ', t: 'ถ้าประเมิน NIHSS ได้ 14 คะแนน หมายความว่าอย่างไร?', h: 'NIHSS: 1–4=เล็กน้อย / 5–15=ปานกลาง / 16–20=ปานกลาง-รุนแรง / ≥21=รุนแรง', o: ['เล็กน้อย — ไม่ต้องรีบ refer', 'ปานกลาง — เข้าเกณฑ์พิจารณา rt-PA และ Thrombectomy', 'รุนแรงมาก — ต้อง refer ทันที ห้ามให้ยาใดๆ', 'ปกติ — ยังไม่เข้าเกณฑ์ใด'], a: 1, e: 'NIHSS 14 = Moderate → เข้าเกณฑ์พิจารณา rt-PA (ถ้าไม่มี C/I) หรือ Thrombectomy ถ้าสงสัย LVO' },
      { g: 'กลุ่มที่ 2 — NIHSS & อาการ', t: 'อาการใดในพระภิกษุรูปนี้บ่งชี้ว่าอาจมี Large Vessel Occlusion (LVO)?', h: 'VAN Signs = Aphasia / Neglect / Eye deviation ร่วมกับ NIHSS ≥6 → สงสัย LVO', o: ['BP สูง 195/105 mmHg', 'ประวัติ AF ใช้ Warfarin', 'พูดไม่ชัด (Aphasia) + แขนซ้ายอ่อนแรง + NIHSS 14', 'O₂Sat 96% RA'], a: 2, e: 'Aphasia + motor deficit + NIHSS ≥6 → VAN positive → สงสัย LVO ต้องแจ้งปลายทางเตรียมทีม Thrombectomy' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'หลักการตรวจ Lab ก่อนให้ rt-PA (alteplase) ข้อใดสอดคล้องที่สุด?', h: 'คัดกรองข้อห้ามสำคัญตาม protocol — สั่งแบบขนานกับ stroke code ไม่ใช่ต้องรอครบทุกรายการเสมอ', o: ['ต้องรอผล Lab ครบทุกชุดเสมอก่อนจึงจะให้ alteplase ได้', 'CBC อย่างเดียวพอ', 'สั่งเจาะควบคู่การดูแลเฉียบพลัน และใช้ผลที่จำเป็น (เช่น glucose, PT/INR, PTT ตามประวัติยา) เพื่อคัดกรองข้อห้าม — ไม่ใช่ต้องรอครบทุกตัวในทุกกรณี', 'PT, INR เท่านั้น'], a: 2, e: 'มักสั่งเจาะพร้อมภาพสมองแบบขนาน โดยใช้ผลที่เกี่ยวกับข้อห้าม (glucose, การแข็งตัวของเลือดตามประวัติยา ฯลฯ) ตาม protocol — ไม่ได้หมายความว่าต้องหยุดรอครบทุกรายการในทุกสถานการณ์ ขึ้นกับดุลยพินิจทีมและข้อบ่งชี้' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'ผล INR = 2.1 มีผลต่อการให้ rt-PA อย่างไร? และยังมีทางเลือกอื่นไหม?', h: 'INR >1.7 = Absolute Exclusion สำหรับ rt-PA แต่ไม่ใช่ข้อห้ามสำหรับ Thrombectomy', o: ['ให้ rt-PA ได้ปกติ INR ต้องสูงกว่า 3.0 ก่อน', 'ให้ rt-PA ได้แต่ลดขนาดยาครึ่งหนึ่ง', 'ห้ามให้ rt-PA เด็ดขาด — แต่ยังพิจารณา Refer Thrombectomy ได้', 'ห้ามให้ทุกอย่าง เพราะ BP สูงด้วย'], a: 2, e: 'INR >1.7 = C/I rt-PA เด็ดขาด ไม่มีข้อยกเว้น แต่ Thrombectomy ไม่มีข้อห้ามเรื่อง INR → Refer ได้ค่ะ' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'BP 195/105 mmHg พยาบาลควรทำอย่างไร?', h: 'SBP >185 หรือ DBP >110 = C/I rt-PA / ระหว่างรอ refer ให้ Keep BP <180/105 mmHg', o: ['ไม่เป็นข้อห้ามใดๆ รอแพทย์สั่งเท่านั้น', 'เป็น C/I rt-PA — Keep BP <180/105 ระหว่างรอ refer และ monitor ต่อเนื่อง', 'ลด BP ให้ปกติก่อน แล้วพิจารณาให้ rt-PA ใหม่', 'ไม่ต้องทำอะไร เพราะไม่ได้ให้ rt-PA อยู่แล้ว'], a: 1, e: 'SBP >185 = C/I rt-PA ระหว่างรอ refer ให้ Keep BP <180/105 เพื่อลดความเสี่ยง hemorrhagic transformation หลัง Thrombectomy' },
      { g: 'กลุ่มที่ 4 — การเตรียม Refer', t: 'ก่อน refer ไปสถาบันประสาทวิทยา พยาบาลต้องเตรียมอะไรบ้าง?', h: 'ปลายทางต้องการข้อมูลและสิ่งของครบก่อนรับผู้ป่วย', o: ['แค่ตัวผู้ป่วย — ของอื่นส่งทีหลังได้', 'CD PACs/ภาพ CT, ใบ refer+Lab, ญาติธรรม/ญาติโยมไปด้วย (ถ้ามา), ใบรับรองสิทธิ, IV line, ยา', 'ใบ refer อย่างเดียวพอ', 'รอให้แพทย์เตรียมทุกอย่างให้ครบก่อน'], a: 1, e: 'ต้องครบ: CD ลง PACs, ใบ refer+Lab, ญาติธรรมหรือญาติโยม (ถ้ามา), ใบสิทธิ, IV line, ยาประจำตัว — ยิ่งครบ ปลายทางเตรียมทีมได้เร็วขึ้น' },
      { g: 'กลุ่มที่ 5 — การสื่อสาร SBAR', t: 'เมื่อโทรประสานสถาบันประสาทวิทยา พยาบาลควรรายงานอะไรบ้าง?', h: 'SBAR = Situation / Background / Assessment / Recommendation', o: ['ชื่อ อายุ และ ward เท่านั้น', 'S:อาการที่พบ → B:โรคประจำตัว/ยา → A:NIHSS/CT/Lab → R:ต้องการรับ/เตรียม Thrombectomy', 'ส่ง LINE ข้อความแทนการโทร', 'รอให้แพทย์โทรเอง'], a: 1, e: 'SBAR: S=stroke พระภิกษุ onset 1.5h / B=HT,DM,AF ใช้ Warfarin / A=NIHSS 14, CT(-), INR 2.1, C/I rt-PA / R=ขอ refer Thrombectomy' },
      { g: 'กลุ่มที่ 5 — การสื่อสาร SBAR', t: 'ระบบแสดง "REFER — Thrombectomy (C/I rt-PA)" พยาบาลควรอธิบายญาติธรรมหรือญาติโยมว่าอย่างไร?', h: 'ผู้ติดตามมักเข้าใจว่าต้องได้รับ "ยาละลายลิ่มเลือด" เสมอ', o: ['"ท่านอาการหนักมาก ไม่มีทางรักษาได้แล้ว"', '"ยาละลายลิ่มเลือดฉีดตรงๆ ไม่ได้เพราะท่านกินยาป้องกันลิ่มเลือดอยู่ แต่ยังส่งต่อเพื่อสอดสายดูดลิ่มเลือดออกโดยตรงได้ ต้องรีบภายใน 24 ชม."', '"ไม่ต้องกังวล รับนอนที่นี่ก่อน ดูอาการไปเรื่อยๆ"', '"รอผลเลือดครบก่อน 3–4 ชม. แล้วค่อยตัดสินใจ"'], a: 1, e: '"ท่านกินยาป้องกันลิ่มเลือดอยู่ ฉีดยาตรงๆ ไม่ได้ค่ะ แต่ยังส่งต่อเพื่อสอดสายเข้าไปดูดลิ่มเลือดออกโดยตรงได้ ต้องทำภายใน 24 ชั่วโมงค่ะ"' }
    ]
  },
  {
    id: 'wakeup',
    title: 'เคส 2 — Wake-up Stroke (ไม่ทราบ onset ชัด — เน้น LSN)',
    shortTitle: 'Wake-up Stroke',
    caseHtml: '<span class="case-tag">พระภิกษุ 72 ปี</span><span class="case-tag">ไม่ใช้ยาละลายลิ่ม/Anticoagulant</span><span class="case-tag">BP ปกติ</span><br>ตื่นนอน <strong>06:30 น.</strong> พบพูดไม่ชัด อ่อนแรงแขนซ้าย — เมื่อคืนนอนหลับปกติ <strong>21:00 น.</strong> ไม่มีอาการผิดปกติ<br>นำส่ง ER <strong>07:45 น.</strong> · <strong>BP 135/85</strong> · O₂Sat 97% RA · CT: No hemorrhage',
    questions: [
      { g: 'กลุ่มที่ 1 — Timeline & Onset', t: 'พระภิกษุ 72 ปี ตื่นมาพบอาการ 06:30 น. — เมื่อคืนนอนหลับปกติ 21:00 น. Last Seen Normal (LSN) และความสัมพันธ์กับ Onset อย่างไร (แนว Wake-up)?', h: 'LSN = เวลาที่รู้ว่ายังปกติดีล่าสุด / Onset แท้อาจไม่ทราบเมื่อตื่นมาพบอาการ', o: ['LSN = Onset = 06:30 น. (ตื่นมาแล้วเป็นเท่านั้น)', 'LSN = เวลาที่ทราบว่าปกติล่าสุด ≈ ก่อนนอน 21:00 น. / Onset แท้ไม่ทราบชัด (รูปแบบ Wake-up)', 'LSN = ไม่ทราบเลย — รอญาติ', 'LSN = เวลาถึง ER'], a: 1, e: 'Wake-up pattern: LSN มักย้อนไปเวลาที่ยังปกติดีล่าสุด (เช่น ก่อนนอน) ส่วน onset แท้อาจไม่ทราบ — ไม่ควรสรุป LSN = เวลาตื่นโดยไม่คิดถึงบริบท' },
      { g: 'กลุ่มที่ 1 — Timeline & Onset', t: 'ไม่มีประวัติ Anticoagulant BP 135/85 mmHg CT ไม่พบเลือดออก — หลักการพิจารณา rt-PA ในกลุ่ม Wake-up (ตามการประเมินทีม + protocol โรงพยาบาล)?', h: 'Wake-up onset ไม่ชัด → มักต้องใช้ advanced imaging (เช่น MRI DWI–FLAIR mismatch หรือ perfusion CT/MRI) ประกอบว่า lesion ยังอยู่ในช่วงที่พิจารณา reperfusion ได้หรือไม่ — ไม่ตัดสินแค่ CT ธรรมดา', o: ['ห้าม rt-PA ทุกกรณีเพราะไม่รู้เวลา onset', 'พิจารณาได้หากทีม + imaging (รวม advanced imaging ตาม protocol) ประเมินแล้วเข้าเกณฑ์ และไม่มีข้อห้ามอื่น', 'ให้ rt-PA ได้ทันทีโดยไม่ต้องมี CT', 'รอ 24 ชม. ค่อยให้'], a: 1, e: 'Wake-up ไม่มีเวลา onset ชัด → ทีมมักใช้ภาพขั้นสูง (MRI DWI–FLAIR mismatch, perfusion CT/MRI ฯลฯ) ประกอบว่าเนื้อเยื่อยังอยู่ในช่วงที่พิจารณา thrombolysis/EVT ได้หรือไม่ แม้ CT ธรรมดาไม่เห็นเลือดออก กรณีนี้ไม่มี anticoag และ BP ดี แต่ยังต้องผ่านเกณฑ์ imaging และ protocol ของโรงพยาบาล' },
      { g: 'กลุ่มที่ 2 — NIHSS & อาการ', t: 'ถ้าประเมิน NIHSS ได้ 12 คะแนน หมายความว่าอย่างไร?', h: 'NIHSS: 1–4=เล็กน้อย / 5–15=ปานกลาง / 16–20=ปานกลาง-รุนแรง / ≥21=รุนแรง', o: ['เล็กน้อย — ไม่ต้องรีบ refer', 'ปานกลาง — เข้าเกณฑ์พิจารณา rt-PA และ/หรือ Thrombectomy ตามทีม', 'รุนแรงมาก — ห้ามให้ยาใดๆ', 'ปกติ'], a: 1, e: 'NIHSS 12 = ปานกลาง → เข้าเกณฑ์พิจารณา pathway เฉียบพลันได้หากเวลาและข้อห้ามอนุญาต' },
      { g: 'กลุ่มที่ 2 — NIHSS & อาการ', t: 'อาการใดในพระภิกษุรูปนี้สนับสนุนให้สงสัย Large Vessel Occlusion (LVO) ร่วมด้วย?', h: 'VAN: Aphasia / Neglect / Eye deviation + NIHSS ≥6', o: ['BP 135/85 mmHg', 'ไม่มีประวัติ Warfarin', 'พูดไม่ชัด + อ่อนแรงแขน + NIHSS 12', 'O₂Sat 97%'], a: 2, e: 'Aphasia + motor deficit + NIHSS ≥6 → น่าสงสัย LVO — แจ้งปลายทางให้เตรียมทางเลือก EVT ตามเกณฑ์' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'หลักการตรวจ Lab ก่อนพิจารณา rt-PA ในกลุ่ม Wake-up ข้อใดเหมาะสมที่สุด?', h: 'ผลที่จำเป็นต่อข้อห้ามตาม protocol — ไม่ใช่ต้องรอครบทุกตัวในทุกกรณี', o: ['ต้องรอผล Lab ครบทุกตัวเสมอก่อนจึงจะให้ยาได้', 'CBC อย่างเดียว', 'สั่งเจาะควบคู่การประเมิน และใช้ผลที่จำเป็น (เช่น glucose, PT/INR, PTT ตามประวัติยา) เพื่อคัดกรองข้อห้าม — ไม่ใช่ต้องรอครบทุกรายการในทุกสถานการณ์', 'รอ discharge ค่อยเจาะ'], a: 2, e: 'เจาะแบบขนานกับการประเมิน ใช้ผลที่เกี่ยวกับข้อห้ามตาม protocol — ไม่ได้หมายความว่าต้องหยุดรอครบทุกรายการในทุกกรณี' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'ผล INR = 1.0 (ไม่ได้ใช้ Warfarin) มีความหมายต่อการให้ rt-PA อย่างไร?', h: 'INR สูง = ข้อห้าม rt-PA / INR ปกติ = ไม่ใช่ข้อห้ามจาก INR อย่างเดียว', o: ['INR ปกติ = ให้ rt-PA ได้เสมอโดยไม่ต้องดูอย่างอื่น', 'ไม่ใช่ข้อห้ามจาก INR — ยังต้องผ่านเกณฑ์เวลา ภาพสมอง และ Lab/ข้อห้ามอื่น', 'INR <2 ห้าม rt-PA', 'ต้องรอ INR >3'], a: 1, e: 'INR ปกติไม่ได้แปลว่าให้ยาได้ทันที แต่ไม่ถูกจำกัดจาก INR — ยังต้องครบเงื่อนไขอื่น' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'BP 135/85 mmHg ในพระภิกษุรูปนี้ — เกี่ยวกับข้อห้าม BP สำหรับ rt-PA อย่างไร?', h: 'เกณฑ์ข้อห้าม BP มัก SBP>185 หรือ DBP>110', o: ['ถือว่าสูงเกินเกณฑ์ห้าม rt-PA ทุกกรณี', 'ช่วงนี้ไม่เข้าเกณฑ์ข้อห้าม BP สำหรับ rt-PA — ยังต้องดูข้อห้ามอื่น', 'ต้องลดให้ต่ำกว่า 90/60 ก่อน', 'ไม่ต้องวัดซ้ำ'], a: 1, e: 'BP ช่วงนี้อยู่ใต้เกณฑ์ข้อห้าม BP ทั่วไปของ rt-PA — ยังต้องประเมินข้อห้ามอื่นครบ' },
      { g: 'กลุ่มที่ 4 — การเตรียม Refer', t: 'หากทีมส่งต่อเพื่อพิจารณา EVT/สถาบัน ต้องเตรียมอะไรบ้าง?', h: 'ชุดข้อมูลครบช่วยปลายทางตัดสินใจเร็ว', o: ['แค่ตัวผู้ป่วย', 'CD PACs/ภาพ CT, ใบ refer+Lab, ญาติธรรม/ญาติโยม (ถ้ามา), สิทธิ, IV line, ยา', 'ใบ refer อย่างเดียว', 'รอแพทย์ทำทุกอย่าง'], a: 1, e: 'ชุดเดียวกับ Fast Track: ข้อมูลภาพ+Lab+การสื่อสาร+ญาติที่เกี่ยวข้อง — ยิ่งครบยิ่งลด delay' },
      { g: 'กลุ่มที่ 5 — การสื่อสาร SBAR', t: 'SBAR กับปลายทาง — ข้อใดเหมาะสมที่สุดสำหรับเคส Wake-up นี้?', h: 'S B A R ครบ และระบุว่าไม่ทราบ onset ชัด — ควรสื่อสารสถานะ advanced imaging ถ้ามี', o: ['ชื่อกับ ward พอ', 'S=Wake-up / อาการ / เวลาที่พบ → B=ไม่มี anticoag → A=NIHSS, CT, advanced imaging/Lab ตามที่มี → R=ขอรับ/เตรียม pathway ตามทีม', 'ส่งแค่ LINE', 'รอแพทย์โทร'], a: 1, e: 'เน้น S ว่าเป็น Wake-up + เวลาที่พบอาการ + LSN ที่ทราบ, B ยา, A ภาพ (รวม advanced imaging ตาม protocol) และ Lab, R ชัดเจน' },
      { g: 'กลุ่มที่ 5 — การสื่อสาร SBAR', t: 'อธิบายญาติธรรม/ญาติโยมเรื่อง Wake-up และการให้ยาละลายลิ่ม?', h: 'อธิบายว่าทีมใช้เวลา + ภาพสมอง (รวม advanced imaging ตาม protocol) + Lab ประกอบ — ไม่ใช่ตัดสินแค่ “ตื่นมาแล้วเป็น”', o: ['"ตื่นมาเป็น = ห้ามรักษาทุกอย่าง"', '"ทีมจะประเมินเวลา ภาพสมอง (บางกรณีต้อง MRI/perfusion) และผลเลือด — หากเข้าเกณฑ์อาจให้ยาละลายลิ่มได้แม้เป็นแบบตื่นมาพบอาการ"', '"ไม่ต้องทำอะไร"', '"รออีกสัปดาห์"'], a: 1, e: 'สื่อสารแบบไม่ตัดสิทธิ์การรักษา — อธิบายว่าทีมใช้ advanced imaging ประกอบการตัดสินใจ ไม่ตัดสินแค่ CT ธรรมดาหรือคำว่า “ตื่นมาแล้วเป็น”' }
    ]
  },
  {
    id: 'nonfast',
    title: 'เคส 3 — นอกช่วง Fast Track (onset ~2 วัน — Conservative)',
    shortTitle: 'นอกช่วงเวลา / Conservative',
    caseHtml: '<span class="case-tag">พระภิกษุ 55 ปี</span><span class="case-tag">อาการเล็กน้อย</span><span class="case-tag">Onset ~2 วัน</span><br>เริ่มอ่อนแรงแขนขวาเล็กน้อยและพูดติดขัดตั้งแต่ประมาณ <strong>2 วันก่อน</strong> อาการคงที่ไม่หนักขึ้น<br>มา ER วันนี้ · <strong>BP 128/78</strong> · O₂Sat 98% RA · CT: ไม่พบเลือดออกเฉียบพลัน (รูปแบบนอก acute reperfusion window)',
    questions: [
      { g: 'กลุ่มที่ 1 — Timeline & Onset', t: 'พระภิกษุ 55 ปี อาการเริ่ม ~2 วันก่อน ชัดเจนว่าไม่ใช่เหตุการณ์เฉียบพลันวันนี้ — สรุปเกี่ยวกับ acute onset/LSN อย่างไร?', h: 'อยู่นอกกรอบเวลาที่ใช้ rt-PA/EVT เฉียบพลันตามที่ระบุในเคส', o: ['LSN=วันนี้, onset=ไม่ทราบ', 'Onset ~48 ชม. ที่แล้ว — อยู่นอก acute window สำหรับยาละลายลิ่มฉีดเฉียบพลันและ EVT ตามบริบทเคส', 'Onset=เวลาถึง ER', 'ยังเป็น TIA 100%'], a: 1, e: 'เมื่อทราบว่าอาการเริ่มนานแล้ว แนวทางหลักไม่ใช่ Fast Track ละลายลิ่มเฉียบพลัน' },
      { g: 'กลุ่มที่ 1 — Timeline & Onset', t: 'แนวทางหลักในการดูแลเคสนี้?', h: 'เน้นประคับประคอง ตามแผนแพทย์ และการป้องกันการเกิดซ้ำ (secondary prevention)', o: ['เร่ง rt-PA ทันที', 'เร่ง Thrombectomy ทุกราย', 'ดูแลเชิงประคับประคอง + ตามแผนแพทย์ (สาเหตุ / ยาตามชี้ขาด / การป้องกันการเกิดซ้ำ) — ไม่ใช่ Fast Track ละลายลิ่มเฉียบพลัน', 'รอ 1 สัปดาห์ค่อยรักษา'], a: 2, e: 'นอกช่วงเวลา acute reperfusion ที่ระบุ — โฟกัสการรักษาตามความจำเป็น ฟื้นฟู และการป้องกันการเกิดซ้ำ (secondary prevention) — ยากันชักไม่ใช่ส่วนหนึ่งของการดูแลประจำทุกรายของ ischemic stroke ยกเว้นมีชักหรือมีข้อบ่งชี้เฉพาะ' },
      { g: 'กลุ่มที่ 2 — NIHSS & อาการ', t: 'ถ้าประเมิน NIHSS ได้ 4 คะแนน หมายความว่าอย่างไร ในบริบทเคสนี้?', h: 'NIHSS 1–4 = เล็กน้อย', o: ['เล็กน้อย — ไม่ใช่กรณี emergent EVT เฉียบพลันจาก stroke วันนี้', 'ปานกลาง — ต้อง EVT ด่วนทุกราย', 'รุนแรงมาก', 'ปกติ'], a: 0, e: 'NIHSS ต่ำ + onset นาน — ไม่ใช่ภาพที่ชี้ไป emergent thrombectomy pathway แบบเดียวกับ LVO ใน window' },
      { g: 'กลุ่มที่ 2 — NIHSS & อาการ', t: 'การประเมินเชิง LVO / emergent Thrombectomy ในเคสนี้เหมาะสมอย่างไร?', h: 'EVT เฉียบพลันมีเกณฑ์เวลาและภาพคลินิก', o: ['ต้อง EVT ภายใน 24 ชม. ทุกราย', 'ไม่ใช่แนวทาง emergent EVT จาก stroke เฉียบพลัน — เน้นประเมินสาเหตุ การป้องกันการเกิดซ้ำ (secondary prevention) และแผนต่อเนื่อง', 'ไม่ต้อง CT', 'ห้ามให้ยาใดๆ'], a: 1, e: 'Onset นาน + NIHSS เล็กน้อย — pathway หลักไม่ใช่ส่ง EVT เร่งด่วนแบบ Fast Track' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'การเจาะเลือดในระยะนี้มีเป้าหมายหลักอย่างไร?', h: 'ไม่ได้ใช้ตัดสิน rt-PA เฉียบพลัน', o: ['ไม่มีประโยชน์', 'เพื่อประเมินความเสี่ยงและวางแผนการรักษา / การป้องกันการเกิดซ้ำ (secondary prevention) — ไม่ใช่เพื่อตัดสินใจ rt-PA เฉียบพลัน', 'เหมือนเคสภายใน 4.5 ชม. อย่างเดียว', 'รอจำหน่ายค่อยเจาะ'], a: 1, e: 'จุดประสงค์เปลี่ยนจาก “ละลายลิ่มด่วน” เป็น “รองรับการรักษาและป้องกันการเกิดซ้ำ” — ไม่ได้หมายความว่าต้องเจาะเหมือน stroke code ทุกอย่าง ขึ้นกับแผนแพทย์' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'การให้ rt-PA แบบละลายลิ่มเฉียบพลันในเคสนี้ (onset ~2 วัน)?', h: 'เกินกรอบ acute thrombolysis', o: ['ให้ได้ถ้า BP ปกติ', 'ไม่เหมาะสม — อยู่นอก window acute thrombolysis ตามบริบทเคส', 'ให้ได้ถ้า NIHSS ต่ำ', 'ให้ได้ทุกเวลา'], a: 1, e: 'ไม่อยู่ในกรอบเวลาที่ใช้ยาฉีดละลายลิ่มเฉียบพลัน' },
      { g: 'กลุ่มที่ 3 — Lab & ข้อห้าม rt-PA', t: 'BP 128/78 mmHg — บทบาทหลักในเคสนี้?', h: 'ไม่ได้เตรียมเพื่อเข้าเกณฑ์ละลายลิ่มเฉียบพลัน', o: ['ลดให้ต่ำกว่า 100 ทันที', 'เฝ้าระวังและดูแลตามอาการ — ไม่ใช่การเตรียม BP เพื่อให้ rt-PA เฉียบพลัน', 'ให้ยกเท้าสูงอย่างเดียว', 'ห้ามวัดความดัน'], a: 1, e: 'เน้น monitoring และรักษาตามแผน ไม่ใช่ลดความดันเพื่อ thrombolysis' },
      { g: 'กลุ่มที่ 4 — การเตรียม Refer', t: 'การส่งต่อ/เอกสารในบริบทนี้เน้นอะไร?', h: 'ไม่ใช่ชุด emergent EVT แบบ Fast Track เสมอไป', o: ['ส่งตัวเปล่า', 'ใบประวัติ ผลตรวจที่มี ยา และแผนการรักษา — consult/follow-up ตามทีม ไม่ใช่ชุด CD เร่ง EVT เป็นหลัก', 'แค่ CT อย่างเดียว', 'รอ 1 เดือน'], a: 1, e: 'เน้นความต่อเนื่องของข้อมูลสำหรับการรักษาและการนัดหมาย' },
      { g: 'กลุ่มที่ 5 — การสื่อสาร SBAR', t: 'SBAR เมื่อ consult อายุรกรรมประสาท (ไม่ใช่ emergent EVT) — ข้อใดเหมาะสม?', h: 'R เป็นการขอความเห็นหรือแผนรองรับ ไม่ใช่ขอรับ EVT ด่วนโดยอัตโนมัติ', o: ['S เท่านั้น', 'S=อาการ+ระยะเวลา → B=โรค/ยา → A=NIHSS CT Lab → R=ขอความเห็นรักษาและแผน secondary prevention', 'ส่ง LINE แทนโทร', 'รอแพทย์'], a: 1, e: 'สื่อสารระยะเวลาชัด + ความต้องการที่สมจริงกับบริบท' },
      { g: 'กลุ่มที่ 5 — การสื่อสาร SBAR', t: 'อธิบายญาติธรรม/ญาติโยมเมื่อเกินช่วงยาละลายลิ่มฉีดเฉียบพลัน?', h: 'ยังมีการรักษาสำคัญอื่น', o: ['"ไม่มีทางรักษา"', '"ตอนนี้อยู่นอกช่วงเวลาที่ให้ยาฉีดละลายลิ่มได้แล้ว ทีมจะเน้นยาป้องกันไม่ให้เกิดเหตุซ้ำ ฟื้นฟู และติดตาม — ยังมีแผนรักษาที่สำคัญ"', '"รอ 3 วันค่อยฉีด"', '"ไม่ต้องกังวล"'], a: 1, e: 'ลดความกลัวว่า “พลาดช่วงแล้วไม่มีอะไรทำ” — อธิบายแผนต่อเนื่อง' }
    ]
  },
  {
    id: 'hemorrhagic-stroke',
    title: 'เคส 4 — Hemorrhagic Stroke (Intracerebral Hemorrhage)',
    shortTitle: 'ICH Case',
    caseHtml: '<span class="case-tag">พระภิกษุ 68 ปี</span><span class="case-tag">HT / ไม่สม่ำเสมอ</span><span class="case-tag">BP สูงมาก</span><br>มาด้วยอาการปวดศีรษะรุนแรงเฉียบพลัน อาเจียน และซึมลง<br><strong>เวลาเริ่มอาการ 09:00 น.</strong> · มาถึง ER 10:00 น.<br>V/S: <strong>BP 220/120 mmHg</strong>, HR 60<br>GCS E3V4M5 · แขนขาขวาอ่อนแรง<br>CT Brain: <strong>Left basal ganglia hemorrhage</strong> ไม่มี IVH<br><em>68-year-old monk with sudden severe headache, vomiting, and decreased consciousness. CT shows intracerebral hemorrhage.</em>',
    questions: [
      { g: 'กลุ่มที่ 1 — Diagnosis', t: 'จากข้อมูล CT brain และอาการ ข้อใดคือ diagnosis ที่เหมาะสมที่สุด?<br><em>Based on CT and clinical presentation, what is the most likely diagnosis?</em>', h: 'ดูจาก CT เป็นหลัก / CT-based diagnosis', o: ['Acute ischemic stroke', 'Intracerebral hemorrhage (ICH)', 'TIA', 'Subarachnoid hemorrhage (SAH)'], a: 1, e: 'พบเลือดออกในเนื้อสมอง (basal ganglia) → ICH<br><em>Bleeding within brain parenchyma indicates intracerebral hemorrhage.</em>' },
      { g: 'กลุ่มที่ 2 — Initial Management', t: 'การจัดการเบื้องต้นที่สำคัญที่สุดในเคสนี้คืออะไร?<br><em>What is the most important initial management?</em>', h: 'prioritize life-threatening issues', o: ['ให้ rt-PA ทันที', 'ควบคุมความดันโลหิต', 'ให้ aspirin', 'ส่งกลับบ้าน'], a: 1, e: 'ICH ต้องควบคุม BP เพื่อลด hematoma expansion<br><em>Blood pressure control reduces risk of hematoma expansion.</em>' },
      { g: 'กลุ่มที่ 3 — Blood Pressure Target', t: 'BP 220/120 mmHg ควรจัดการอย่างไร?<br><em>How should BP 220/120 mmHg be managed?</em>', h: 'ICH BP management', o: ['ไม่ต้องลด BP', 'ลด BP อย่างรวดเร็วให้ &lt;140 systolic (ตาม protocol)', 'เพิ่ม BP', 'รอ 24 ชม.'], a: 1, e: 'Guideline แนะนำลด SBP ~140 mmHg อย่างปลอดภัย<br><em>Guidelines support lowering SBP to around 140 mmHg.</em>' },
      { g: 'กลุ่มที่ 4 — Thrombolysis', t: 'ผู้ป่วยรายนี้สามารถให้ rt-PA ได้หรือไม่?<br><em>Can this patient receive thrombolysis (rt-PA)?</em>', h: 'absolute contraindication', o: ['ให้ได้', 'ห้ามให้', 'ให้ได้ถ้า BP ลดลง', 'รอ INR ก่อน'], a: 1, e: 'มี intracranial hemorrhage → ห้าม rt-PA<br><em>Intracranial bleeding is an absolute contraindication.</em>' },
      { g: 'กลุ่มที่ 5 — Clinical Deterioration', t: 'อาการใดบ่งบอกว่าผู้ป่วยแย่ลง (ต้องรีบแจ้งแพทย์)?<br><em>Which sign suggests clinical deterioration?</em>', h: 'watch for neuro decline', o: ['BP ลดลงเล็กน้อย', 'GCS ลดลง', 'พูดชัดขึ้น', 'กินได้'], a: 1, e: 'GCS ลดลง → อาจมี hematoma expansion หรือ increased ICP<br><em>Declining GCS may indicate worsening intracranial pressure.</em>' },
      { g: 'กลุ่มที่ 6 — Cause', t: 'สาเหตุที่พบบ่อยที่สุดของ ICH ในเคสนี้คืออะไร?<br><em>Most likely cause of ICH in this patient?</em>', h: 'location + HT', o: ['Hypertension', 'Cardioembolism', 'Infection', 'Hypoglycemia'], a: 0, e: 'Basal ganglia hemorrhage มักเกิดจาก hypertension<br><em>Hypertensive vasculopathy commonly causes deep ICH.</em>' },
      { g: 'กลุ่มที่ 7 — Nursing Priority', t: 'การพยาบาลที่สำคัญที่สุดในระยะแรกคืออะไร?<br><em>Key nursing priority?</em>', h: 'ABC + neuro monitoring', o: ['ให้ผู้ป่วยเดิน', 'monitor neuro sign + BP อย่างใกล้ชิด', 'งดวัด BP', 'ให้กินอาหารทันที'], a: 1, e: 'ต้อง monitor neurological status และ BP อย่างใกล้ชิด<br><em>Close neurological and BP monitoring is essential.</em>' },
      { g: 'กลุ่มที่ 8 — Complication', t: 'ภาวะแทรกซ้อนที่ต้องเฝ้าระวังคืออะไร?<br><em>Key complication to monitor?</em>', h: 'ICH complication', o: ['Hematoma expansion', 'Hypoglycemia', 'Asthma', 'Appendicitis'], a: 0, e: 'hematoma expansion เป็นภาวะแทรกซ้อนสำคัญในช่วงแรก<br><em>Hematoma expansion is a major early complication.</em>' },
      { g: 'กลุ่มที่ 9 — Seizure', t: 'ควรให้ยากันชัก prophylaxis ทุกรายหรือไม่?<br><em>Should all ICH patients receive prophylactic antiepileptics?</em>', h: 'guideline concept', o: ['ให้ทุกราย', 'ไม่จำเป็น ให้เมื่อมี seizure', 'ห้ามใช้', 'ให้เฉพาะ BP สูง'], a: 1, e: 'ไม่แนะนำ routine prophylaxis ถ้าไม่มี seizure<br><em>Routine prophylaxis is not recommended unless seizures occur.</em>' },
      { g: 'กลุ่มที่ 10 — Communication (SBAR)', t: 'SBAR ที่เหมาะสมในเคสนี้คือข้อใด?<br><em>Best SBAR communication?</em>', h: 'clear hemorrhage communication', o: ['รายงานว่าเป็น stroke เฉย ๆ', 'S=ICH + GCS ลด + BP สูง → B=HT → A=CT hemorrhage → R=admit ICU / neurosurgery consult', 'ส่ง LINE อย่างเดียว', 'รอแพทย์'], a: 1, e: 'ต้องสื่อสารว่าเป็น hemorrhagic stroke + severity ชัดเจน<br><em>Clear communication of hemorrhagic stroke and severity is essential.</em>' }
    ]
  },
  {
    id: 'nihss-training',
    title: 'แบบฝึก NIHSS สำหรับพยาบาล / NIHSS Training for Nurses',
    shortTitle: 'NIHSS Training',
    caseHtml: '<span class="case-tag">Nurse Training</span><span class="case-tag">NIHSS Basics</span><span class="case-tag">Thai / English</span><br>แบบฝึกประเมิน <strong>NIHSS (National Institutes of Health Stroke Scale)</strong> สำหรับพยาบาล ฝึกการให้คะแนนเบื้องต้นจากอาการที่พบบ่อยในผู้ป่วย stroke<br><em>Basic bilingual quiz for nurses to practice NIHSS scoring in common stroke scenarios.</em>',
    questions: [
      { g: 'กลุ่มที่ 1 — Level of Consciousness (LOC) / ระดับความรู้สึกตัว', t: 'ผู้ป่วยลืมตาเองได้ แต่ไม่ตอบคำถาม และไม่ทำตามคำสั่งง่าย ๆ เช่น “หลับตา–ลืมตา” หรือ “กำมือ”<br><em>The patient opens eyes spontaneously, but does not answer questions and does not follow simple commands.</em>', h: 'ประเมินระดับความรู้สึกตัวเบื้องต้น / Assess basic level of consciousness', o: ['0 = ปกติ / Alert and responsive', '1 = ไม่ปกติ — ไม่ตอบ/ไม่ทำตามคำสั่ง แต่ยังไม่ถึงขั้นไม่ตอบสนองทั้งหมด / Not alert; not obeying or answering, but not unresponsive', '2 = ต้องกระตุ้นซ้ำ ๆ / Requires repeated stimulation', '3 = ไม่ตอบสนอง / Unresponsive'], a: 1, e: 'ไม่ตอบและไม่ทำตามคำสั่ง = ไม่ใช่ปกติ (0) — ในแบบฝึกนี้ให้เลือกระดับที่บ่งว่ามี LOC บกพร่องแต่ยังไม่ถึงขั้นไม่ตอบสนอง (1) การให้คะแนน 1a จริงควรอ้างอิงแผ่นคะแนน NIHSS ของสถาบัน<br><em>Impaired LOC without being totally unresponsive fits this teaching item; use your site\'s official NIHSS scoring sheet in practice.</em>' },
      { g: 'กลุ่มที่ 2 — LOC Questions / คำถามพื้นฐาน', t: 'ถามผู้ป่วยว่า “ตอนนี้เดือนอะไร?” และ “อายุเท่าไร?” ผู้ป่วยตอบผิดทั้ง 2 ข้อ<br><em>You ask: “What month is it?” and “How old are you?” The patient answers both incorrectly.</em>', h: 'ข้อ NIHSS นี้ให้คะแนนจากจำนวนคำตอบที่ถูก / Score based on number of correct answers', o: ['0 = ตอบถูกทั้ง 2 ข้อ / Both correct', '1 = ตอบถูก 1 ข้อ / One correct', '2 = ตอบผิดทั้ง 2 ข้อ / Both incorrect'], a: 2, e: 'ข้อ LOC Questions: ตอบผิดทั้งสองข้อ = 2 คะแนน<br><em>For LOC questions, both incorrect answers score 2 points.</em>' },
      { g: 'กลุ่มที่ 3 — LOC Commands / ทำตามคำสั่ง', t: 'สั่งให้ผู้ป่วย “หลับตา–ลืมตา” และ “กำมือ–ปล่อยมือ” ผู้ป่วยทำได้ถูกเพียง 1 อย่าง<br><em>You ask the patient to open/close the eyes and grip/release the hand. The patient performs only one command correctly.</em>', h: 'นับจำนวนคำสั่งที่ทำได้ถูกต้อง / Count correct commands', o: ['0 = ทำถูกทั้ง 2 อย่าง / Both correct', '1 = ทำถูก 1 อย่าง / One correct', '2 = ทำไม่ได้ทั้ง 2 อย่าง / Neither correct'], a: 1, e: 'ทำตามคำสั่งถูกเพียง 1 ข้อ = 1 คะแนน<br><em>Only one correct command scores 1 point.</em>' },
      { g: 'กลุ่มที่ 4 — Facial Palsy / กล้ามเนื้อใบหน้า', t: 'ให้ผู้ป่วยยิ้ม เห็นมุมปากซ้ายตกเล็กน้อย แต่ยังขยับใบหน้าได้ค่อนข้างดี<br><em>When asked to smile, there is mild left facial asymmetry, but the face still moves fairly well.</em>', h: 'แยกระหว่าง mild กับ complete facial weakness / Distinguish mild from complete palsy (NIHSS 0–2 เท่านั้น)', o: ['0 = ปกติ / Normal', '1 = อ่อนแรงเล็กน้อย / Minor facial weakness', '2 = อ่อนแรงบางส่วนถึงเกือบ/ทั้งหมดด้านล่างใบหน้า / Partial to complete lower facial paralysis'], a: 1, e: 'มุมปากตกเล็กน้อย = minor facial palsy → 1 คะแนน<br><em>Mild asymmetry is scored as minor facial weakness, 1 point.</em>' },
      { g: 'กลุ่มที่ 5 — Motor Arm / แขน', t: 'ให้ผู้ป่วยยกแขนซ้ายค้างไว้ ผู้ป่วยยกได้ แต่แขนค่อย ๆ ตกลงก่อนครบเวลาที่กำหนด<br><em>The patient can raise the left arm, but it drifts down before the required holding time is completed.</em>', h: 'คำสำคัญคือ drift / The key concept is drift', o: ['0 = ค้างได้ปกติ / No drift', '1 = มี drift / Drift', '2 = ต้านแรงโน้มถ่วงได้ช่วงสั้น / Some effort against gravity', '3 = ยกไม่พ้นเตียง แต่มีการขยับ / No effort against gravity', '4 = ไม่ขยับเลย / No movement'], a: 1, e: 'ยกได้แต่ตกลงก่อนเวลา = drift → 1 คะแนน<br><em>If the arm initially lifts but drifts down, this is scored as 1 point.</em>' },
      { g: 'กลุ่มที่ 6 — Motor Leg / ขา', t: 'ให้ผู้ป่วยยกขาขวา แต่ไม่สามารถยกขึ้นจากเตียงได้เลย และไม่มีการเคลื่อนไหว<br><em>The patient is asked to lift the right leg, but cannot lift it off the bed and shows no movement.</em>', h: 'ไม่มีการเคลื่อนไหว = คะแนนสูงสุดของข้อนี้ / No movement = highest score for this item', o: ['0 = ปกติ / Normal', '1 = มี drift / Drift', '2 = ต้านแรงโน้มถ่วงได้บ้าง / Some effort against gravity', '3 = ขยับได้แต่ไม่ยกพ้นเตียง / No effort against gravity', '4 = ไม่ขยับเลย / No movement'], a: 4, e: 'ไม่ขยับเลย = 4 คะแนน<br><em>No movement at all scores 4 points.</em>' },
      { g: 'กลุ่มที่ 7 — Language / Aphasia / ภาษา', t: 'ผู้ป่วยพูดได้เป็นคำ ๆ แต่เรียงประโยคไม่ได้ ตอบคำถามไม่ค่อยตรง และเข้าใจคำสั่งได้ไม่ดี<br><em>The patient speaks in single words, cannot form proper sentences, answers poorly, and has impaired comprehension.</em>', h: 'ข้อ language ดูทั้งการพูดและความเข้าใจ / Language item considers both expression and comprehension', o: ['0 = ปกติ / Normal', '1 = บกพร่องเล็กน้อย / Mild aphasia', '2 = บกพร่องปานกลาง / Moderate aphasia', '3 = รุนแรงมากหรือแทบสื่อสารไม่ได้ / Severe aphasia'], a: 2, e: 'พูดได้บางส่วนแต่สื่อสารไม่ดีชัดเจน = moderate aphasia → 2 คะแนน<br><em>Partial but clearly impaired communication fits moderate aphasia, 2 points.</em>' },
      { g: 'กลุ่มที่ 8 — Dysarthria / พูดไม่ชัด', t: 'ผู้ป่วยพูดไม่ชัด ฟังยาก แต่ยังพอเข้าใจคำพูดได้<br><em>The patient has slurred speech. It is difficult to understand, but speech is still understandable.</em>', h: 'แยก dysarthria ออกจาก aphasia / Distinguish dysarthria from aphasia', o: ['0 = ปกติ / Normal articulation', '1 = พูดไม่ชัดเล็กน้อยถึงปานกลาง / Mild to moderate dysarthria', '2 = พูดไม่ชัดมากจนเข้าใจยากมากหรือไม่ได้ / Severe dysarthria'], a: 1, e: 'พูดไม่ชัดแต่ยังพอเข้าใจได้ = 1 คะแนน<br><em>If speech is slurred but still understandable, score 1 point.</em>' },
      { g: 'กลุ่มที่ 9 — Neglect / Inattention / การละเลย', t: 'เมื่อกระตุ้นพร้อมกันสองข้าง ผู้ป่วยรับรู้เฉพาะด้านขวา และไม่สนใจด้านซ้าย<br><em>With bilateral simultaneous stimulation, the patient notices only the right side and neglects the left.</em>', h: 'ข้อนี้ช่วยบอก cortical deficit / This item suggests cortical dysfunction', o: ['0 = ไม่มี neglect / No neglect', '1 = มี neglect เล็กน้อย / Mild neglect', '2 = neglect ชัดเจน / Profound neglect'], a: 2, e: 'ไม่รับรู้ด้านซ้ายชัดเจน = neglect เด่น → 2 คะแนน<br><em>Clear neglect of one side is scored as 2 points.</em>' },
      { g: 'กลุ่มที่ 10 — Clinical Integration / สรุปเชิงคลินิก', t: 'ถ้าผู้ป่วยมีอ่อนแรงแขนขาซีกหนึ่ง ร่วมกับ aphasia/neglect และ NIHSS รวม ≥ 6 ควรคิดถึงอะไรเพิ่ม?<br><em>If a patient has unilateral weakness plus aphasia or neglect, and the total NIHSS is ≥ 6, what should you additionally suspect?</em>', h: 'ใช้ NIHSS เพื่อช่วยคิดถึง LVO / NIHSS can help raise suspicion for LVO', o: ['ไม่ต้องคิดอะไรเพิ่ม / No further concern', 'สงสัย LVO และรีบแจ้งทีม stroke / Suspect LVO and notify the stroke team urgently', 'รอดูอาการที่ ward ก่อน / Observe first on the ward', 'ให้ discharge ได้ / Safe for discharge'], a: 1, e: 'NIHSS สูงร่วมกับ cortical sign เช่น aphasia หรือ neglect ควรคิดถึง LVO และรีบ activate pathway<br><em>A higher NIHSS with cortical signs should raise concern for LVO and prompt urgent stroke-team activation.</em>' }
    ]
  }
];
